image: docker.io/qazando/appium-maven

stages:
  - test

test-job:
  stage: test
  script:
    - mvn test -Dcucumber.filter.tags="@Regressive" -Dplatform=devicefarm_android -Ddevice="Google Pixel 7 Pro" -Dosversion=13.0 -Duser=dernivalliandro_HC5zlF -Dkey=sNwiuaTaDB2TbfPcVzi1