image: docker.io/qazando/appium-maven

stages:
  - test

test-job:
  stage: test
  script:
    - mvn test -Dcucumber.filter.tags="@Smoke" -Dplatform=devicefarm_android -Ddevice="Motorola Moto G71 5G" -Dosversion=11.0 -Duser=dernivalliandro_HC5zlF -Dkey=sNwiuaTaDB2TbfPcVzi1