image: docker.io/qazando/appium-maven

stages:
  - test

test-job:
  stage: test
  script:
    - mvn test -Dcucumber.filter.tags="@Regressive" -Dplatform=devicefarm_ios -Ddevice="iPhone 14 Pro Max" -Dosversion=16 -Duser=dernivalliandro_HC5zlF -Dkey=sNwiuaTaDB2TbfPcVzi1